### ISSUE TITLE
Progress Callback?

### ISSUE THREAD

**Issue by dobrado76** [dobrado76/Stable-Diffusion-Unity-Integration#6]
### Discussed in https://github.com/dobrado76/Stable-Diffusion-Unity-Integration/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **albrrt** January 30, 2023</sup>
Hi @dobrado76 I am working on a solution to prevent Editor from hanging while waiting for an image to return. 

See https://github.com/albrrt/Stable-Diffusion-Unity-Integration/commit/0187e8ec220ddb69e9116e893fca417412a39949

It would be good to add some form of progress callback to this, so we don't toggle between windows to check progress.
 
Would this involve making a separate call to the `/sdapi/v1/progress` endpoint? 

I'd be interested to hear your thoughts</div>

**Comment by dobrado76** [comment]
I've done a quick and dirty asynchronous progress callback. Let me know what you think @albrrt.

**Comment by albrrt** [comment]
Thanks for the update. 

There seems to be an issue with getting the StableDiffusionConfiguration so I couldn't get it to work, 
but I understand the logic of the progress bar looking at the code.

Here's the error I get after pulling your changes, opening the Editor, loading the models and hitting the Generate button.
(Models loaded fine)

```
NullReferenceException: Object reference not set to an instance of an object
StableDiffusionGenerator.UpdateGenerationProgress () (at Assets/Stable-Diffusion-Unity-Integration/Scripts/StableDiffusionGenerator.cs:19)
StableDiffusionImage+<GenerateAsync>d__22.MoveNext () (at Assets/Stable-Diffusion-Unity-Integration/Scripts/StableDiffusionImage.cs:231)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <4746c126b0b54f3b834845974d1a9190>:0)
```

**Comment by albrrt** [comment]
Found a fix - the private config reference needed removing see https://github.com/dobrado76/Stable-Diffusion-Unity-Integration/commit/a657de759c539dd1efbcca3ce276deee0a1e2c98
